CREATE DATABASE HOTELERIA;
USE HOTELERIA;

CREATE TABLE HOTEL (
  ID_HOTEL INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(120) NOT NULL,
  DIRECCION VARCHAR(200),
  CIUDAD VARCHAR(100),
  CATEGORIA TINYINT,
  ESTADO ENUM('ACTIVO','INACTIVO') NOT NULL DEFAULT 'ACTIVO'
) ENGINE=INNODB;

CREATE TABLE TIPO_HABITACION (
  ID_TIPO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(60) NOT NULL,
  DESCRIPCION VARCHAR(200),
  CAPACIDAD TINYINT NOT NULL,
  PRECIO_BASE DECIMAL(10,2) NOT NULL,
  CONSTRAINT CHK_TIPO_CAPACIDAD CHECK (CAPACIDAD >= 1),
  CONSTRAINT CHK_TIPO_PRECIO CHECK (PRECIO_BASE >= 0)
) ENGINE=INNODB;

CREATE TABLE HABITACION (
  ID_HABITACION INT AUTO_INCREMENT PRIMARY KEY,
  ID_HOTEL INT NOT NULL,
  ID_TIPO INT NOT NULL,
  NUMERO VARCHAR(10) NOT NULL,
  PISO INT,
  ESTADO ENUM('DISPONIBLE','OCUPADA','MANTENIMIENTO','BLOQUEADA') NOT NULL DEFAULT 'DISPONIBLE',
  UNIQUE KEY UQ_HABITACION_HOTEL_NUMERO (ID_HOTEL, NUMERO),
  CONSTRAINT FK_HABITACION_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL),
  CONSTRAINT FK_HABITACION_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO_HABITACION(ID_TIPO)
) ENGINE=INNODB;

CREATE TABLE TEMPORADA (
  ID_TEMPORADA INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(60) NOT NULL,
  FECHA_INICIO DATE NOT NULL,
  FECHA_FIN DATE NOT NULL,
  INCREMENTO_PORCENTUAL DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  CONSTRAINT CHK_TEMPORADA_RANGO CHECK (FECHA_FIN >= FECHA_INICIO)
) ENGINE=INNODB;

CREATE TABLE TARIFA (
  ID_TARIFA INT AUTO_INCREMENT PRIMARY KEY,
  ID_TIPO INT NOT NULL,
  ID_TEMPORADA INT NOT NULL,
  PRECIO_FINAL DECIMAL(10,2) NOT NULL,
  UNIQUE KEY UQ_TARIFA_TIPO_TEMPORADA (ID_TIPO, ID_TEMPORADA),
  CONSTRAINT FK_TARIFA_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO_HABITACION(ID_TIPO),
  CONSTRAINT FK_TARIFA_TEMPORADA FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADA(ID_TEMPORADA),
  CONSTRAINT CHK_TARIFA_PRECIO CHECK (PRECIO_FINAL >= 0)
) ENGINE=INNODB;

CREATE TABLE CLIENTE (
  ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
  TIPO_DOCUMENTO ENUM('CC','CE','TI','PP','OTRO') NOT NULL DEFAULT 'CC',
  NUMERO_DOCUMENTO VARCHAR(30) NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  APELLIDO VARCHAR(80) NOT NULL,
  CORREO VARCHAR(120),
  TELEFONO VARCHAR(30),
  UNIQUE KEY UQ_CLIENTE_DOC (TIPO_DOCUMENTO, NUMERO_DOCUMENTO),
  UNIQUE KEY UQ_CLIENTE_CORREO (CORREO)
) ENGINE=INNODB;

CREATE TABLE RESERVA (
  ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
  ID_CLIENTE INT NOT NULL,
  ID_HABITACION INT NOT NULL,
  FECHA_INICIO DATE NOT NULL,
  FECHA_FIN DATE NOT NULL,
  ADULTOS TINYINT NOT NULL DEFAULT 1,
  NINOS TINYINT NOT NULL DEFAULT 0,
  ESTADO ENUM('PENDIENTE','CONFIRMADA','CANCELADA','CHECKIN','CHECKOUT','NO_SHOW') NOT NULL DEFAULT 'PENDIENTE',
  TARIFA_APLICADA DECIMAL(10,2) NOT NULL,
  MONEDA CHAR(3) NOT NULL DEFAULT 'COP',
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CHK_RESERVA_RANGO CHECK (FECHA_FIN > FECHA_INICIO),
  CONSTRAINT CHK_RESERVA_ADULTOS CHECK (ADULTOS >= 1),
  CONSTRAINT CHK_RESERVA_NINOS CHECK (NINOS >= 0),
  CONSTRAINT FK_RESERVA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  CONSTRAINT FK_RESERVA_HABITACION FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION(ID_HABITACION)
) ENGINE=INNODB;

CREATE TABLE PAGO (
  ID_PAGO INT AUTO_INCREMENT PRIMARY KEY,
  ID_RESERVA INT NOT NULL,
  FECHA_PAGO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  METODO ENUM('EFECTIVO','TARJETA','TRANSFERENCIA','PSE','OTRO') NOT NULL,
  MONTO DECIMAL(10,2) NOT NULL,
  REFERENCIA VARCHAR(60),
  UNIQUE KEY UQ_PAGO_RESERVA (ID_RESERVA),
  CONSTRAINT CHK_PAGO_MONTO CHECK (MONTO >= 0),
  CONSTRAINT FK_PAGO_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE SERVICIO (
  ID_SERVICIO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200),
  PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
  TIPO ENUM('ALOJAMIENTO','ALIMENTO','TRANSPORTE','SPA','TOUR','OTRO') NOT NULL DEFAULT 'OTRO',
  ACTIVO BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT CHK_SERVICIO_PRECIO CHECK (PRECIO_UNITARIO >= 0)
) ENGINE=INNODB;

CREATE TABLE RESERVA_SERVICIO (
  ID_RESERVA INT NOT NULL,
  ID_SERVICIO INT NOT NULL,
  CANTIDAD INT NOT NULL DEFAULT 1,
  PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID_RESERVA, ID_SERVICIO),
  CONSTRAINT CHK_RS_CANTIDAD CHECK (CANTIDAD >= 1),
  CONSTRAINT CHK_RS_PRECIO CHECK (PRECIO_UNITARIO >= 0),
  CONSTRAINT FK_RS_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA) ON DELETE CASCADE,
  CONSTRAINT FK_RS_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
) ENGINE=INNODB;

CREATE TABLE CHECKIN (
  ID_CHECKIN INT AUTO_INCREMENT PRIMARY KEY,
  ID_RESERVA INT NOT NULL,
  FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  OBSERVACION VARCHAR(200),
  UNIQUE KEY UQ_CHECKIN_RESERVA (ID_RESERVA),
  CONSTRAINT FK_CHECKIN_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE CHECKOUT (
  ID_CHECKOUT INT AUTO_INCREMENT PRIMARY KEY,
  ID_RESERVA INT NOT NULL,
  FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CARGOS_EXTRA DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  OBSERVACION VARCHAR(200),
  UNIQUE KEY UQ_CHECKOUT_RESERVA (ID_RESERVA),
  CONSTRAINT CHK_CHECKOUT_CARGOS CHECK (CARGOS_EXTRA >= 0),
  CONSTRAINT FK_CHECKOUT_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA) ON DELETE CASCADE
) ENGINE=INNODB;
